# This workflow updates the packages on PyPI

name: build & test

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'

jobs:
  build-n-publish:  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -r requirements.txt
        
    - name: Install and upload if not up to date
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        pip install lyncs_cppyy==$(lyncs_setuptools version) || (
          python setup.py sdist
          twine upload dist/*
          count=0
          while ! pip install lyncs_cppyy==$(lyncs_setuptools version) && [ $count -lt 20 ]; do
            sleep 1
            count=$((count+1))
          done
        )

    - name: Run tests
      run: |
        pip install lyncs_cppyy[test]==$(lyncs_setuptools version)
        pytest -v --cov=lyncs_cppyy --cov-report=xml
        export CODECOV_TOKEN="${{ secrets.CODECOV_TOKEN }}"
        bash <(curl -s https://codecov.io/bash) -f ./coverage.xml -n lyncs_cppyy
